import React from 'react';
import { FTA_LOGO_URL, InfoLine } from '../reportShared';

export function VatReportHeader({ period, generatedDate, vatModeLabel, businessName, trn, emirate }: any) {
  return <header className='tax-report-header vat-report-header'>
    <div className='tax-report-brand'>
      <img src={FTA_LOGO_URL} alt='Federal Tax Authority logo' className='tax-report-logo' crossOrigin='anonymous' referrerPolicy='no-referrer' />
      <div><h1>UAE VAT201 Return Summary</h1><p>Generated by UAE VAT &amp; Tax Filing Assistant</p></div>
    </div>
    <div className='tax-report-meta compact'>
      <InfoLine label='Business Name' value={businessName || '—'} />
      <InfoLine label='TRN' value={trn || '—'} />
      <InfoLine label='Emirate' value={emirate} />
      <InfoLine label='VAT Period' value={period} />
      <InfoLine label='Prepared Date' value={generatedDate} />
      <InfoLine label='VAT Mode' value={vatModeLabel} />
    </div>
  </header>;
}
