import React from 'react';

export function VatReportFooter() {
  return <footer className='tax-report-footer vat-report-footer'>
    <div><span>Generated by:</span><strong>uaevat.live | UAE VAT &amp; Tax Filing Assistant</strong></div>
    <div><span>Powered by ecashbiz ERP</span></div>
    <p>This report is a calculation assistance summary only. Verify all figures and eligibility before official FTA submission.</p>
  </footer>;
}
