import React from 'react';
import { calculateCorporateTax } from './lib/corporateTaxCalculator';
import { ExportActions, FormSection, TaxSummaryCard, money } from './components/common.jsx';
import { TAX_CONFIG } from './lib/taxConfig';
import { downloadPdfReport } from './lib/pdfGenerator';
const steps=['Company Details','Income','Expenses','Taxable Profit','Tax Calculation','Export'];
export function CorporateTaxWizard({data,setData,onSave,onReset,onProgressChange}){const [step,setStep]=React.useState(1); const r=calculateCorporateTax(data);
React.useEffect(()=>{onProgressChange?.(Math.round((step/6)*100));},[step,onProgressChange]);
const missingRequired = !data.companyName || !data.taxRegistrationNumber || !data.businessActivity;
return <div><FormSection title={`Corporate Tax Wizard: ${steps[step-1]}`}>
{step===1&&<div className='form-grid three'><input placeholder='Company name' value={data.companyName} onChange={e=>setData({...data,companyName:e.target.value})}/><input placeholder='Tax registration number' value={data.taxRegistrationNumber} onChange={e=>setData({...data,taxRegistrationNumber:e.target.value})}/><input placeholder='Business activity' value={data.businessActivity} onChange={e=>setData({...data,businessActivity:e.target.value})}/></div>}
{step===2&&<div className='form-grid three'><input type='number' min='0' placeholder='Total revenue' value={data.revenue} onChange={e=>setData({...data,revenue:e.target.value})}/><input type='number' min='0' placeholder='Other income' value={data.otherIncome} onChange={e=>setData({...data,otherIncome:e.target.value})}/><input type='number' min='0' placeholder='Exempt income' value={data.exemptIncome} onChange={e=>setData({...data,exemptIncome:e.target.value})}/></div>}
{step===3&&<div className='form-grid three'><input type='number' min='0' placeholder='Direct expenses' value={data.directExpenses} onChange={e=>setData({...data,directExpenses:e.target.value})}/><input type='number' min='0' placeholder='Admin/general expenses' value={data.adminExpenses} onChange={e=>setData({...data,adminExpenses:e.target.value})}/><input type='number' min='0' placeholder='Non-deductible expenses' value={data.nonDeductibleExpenses} onChange={e=>setData({...data,nonDeductibleExpenses:e.target.value})}/></div>}
{step===4&&<div className='form-grid three'><input type='number' placeholder='Accounting profit' value={data.accountingProfit} onChange={e=>setData({...data,accountingProfit:e.target.value})}/><input type='number' placeholder='Add-back adjustments' value={data.addBackAdjustments} onChange={e=>setData({...data,addBackAdjustments:e.target.value})}/><input type='number' placeholder='Deductible adjustments' value={data.deductibleAdjustments} onChange={e=>setData({...data,deductibleAdjustments:e.target.value})}/></div>}
{step>=5&&<div className='grid-section'><TaxSummaryCard label='Threshold (0%)' value={money(TAX_CONFIG.corporateTaxThreshold)}/><TaxSummaryCard label='Taxable above threshold' value={money(r.taxableAboveThreshold)}/><TaxSummaryCard label='Rate' value='9%'/><TaxSummaryCard label='Final estimated tax payable' value={money(r.taxPayable)}/><p>For preparation only. Please verify before official FTA submission.</p></div>}
</FormSection><div className='wizard-nav no-print'><button onClick={()=>setStep(s=>Math.max(1,s-1))} disabled={step===1}>Back</button><button onClick={()=>setStep(s=>Math.min(6,s+1))} disabled={step===6 || (step===1 && missingRequired)}>Continue</button></div>{step===6&&<ExportActions onSave={onSave} onReset={onReset} onPrint={()=>window.print()} onPdf={()=>downloadPdfReport('corporate-tax-report')}/>}</div>}
