import React from 'react';
import { AppBar, Box, Card, CardContent, Chip, Container, Grid, IconButton, Menu, MenuItem, Stack, Toolbar, Typography, Button, Link } from '@mui/material';
import MenuIcon from '@mui/icons-material/Menu';
import HomeRoundedIcon from '@mui/icons-material/HomeRounded';
import { VatWizard } from './VatWizard';
import { CorporateTaxWizard } from './CorporateTaxWizard';
import { draftStorage } from './lib/localDraftStorage';
import { buildMonthlyEntries, calculateVat } from './lib/vatCalculator';
import { calculateCorporateTax } from './lib/corporateTaxCalculator';
import { money, TaxSummaryCard, WorkspaceHeader } from './components/common.jsx';
import { TaxModuleCard } from './components/TaxModuleCard';
import { InstallAppPrompt } from '../../components/InstallAppPrompt';
import { formatVatPeriodLabel, inferSelectionFromDates, getPeriodFromSelection } from './lib/vatPeriod';
import { VAT_PRICING_MODES, normalizeVatPricingMode } from './lib/vatPricing';
const currentYear=new Date().getFullYear(); const workspaceSettingsDefault={vatPricingMode:VAT_PRICING_MODES.EXCLUSIVE};
const vatDefault={ businessName:'', trn:'', filingFrequency:'Quarterly', filingYear:currentYear, filingMonth:'January', filingQuarter:'Q1', filingStartMonth:'January', taxPeriodStart:'', taxPeriodEnd:'', standardRatedSales:0, zeroRatedSales:0, exemptSales:0, standardRatedPurchases:0, recoverableInputVat:0, nonRecoverableVat:0, previousAdjustment:0, badDebtRelief:0, adjustmentNotes:'', monthlyEntries:[], vatPricingMode:workspaceSettingsDefault.vatPricingMode };
const ctDefault={ companyName:'', taxRegistrationNumber:'', financialYearStart:'', financialYearEnd:'', businessActivity:'', revenue:0, otherIncome:0, exemptIncome:0, directExpenses:0, adminExpenses:0, nonDeductibleExpenses:0, accountingProfit:0, addBackAdjustments:0, deductibleAdjustments:0 };
const navLinks=[{label:'FTA Login',href:'https://eservices.tax.gov.ae/#/Logon'},{label:'VAT Guidelines',href:'https://tax.gov.ae/en/taxes/Vat/vat.topics.aspx'},{label:'Corporate Tax Guidelines',href:'https://tax.gov.ae/en/taxes/corporate.tax/corporate.tax.topics.aspx'},{label:'FTA YouTube',href:'https://www.youtube.com/@uaetax'}];
const getVatStatus=(n)=>n>0?['VAT Payable','error',money(n)]:n<0?['VAT Refundable','success',money(Math.abs(n))]:['VAT Payable / Refundable','primary',money(0)];
const normalizeVatDraft=(input,workspaceSettings)=>{const merged={...vatDefault,...input,vatPricingMode:normalizeVatPricingMode(input?.vatPricingMode||workspaceSettings.vatPricingMode)}; const selection=inferSelectionFromDates(merged); const period=getPeriodFromSelection(selection); const next={...merged,...selection,...period}; next.monthlyEntries=buildMonthlyEntries(next); return next;};
function Header(){const [a,setA]=React.useState(null);return <AppBar position='sticky' color='inherit' elevation={0} sx={{borderBottom:'1px solid #dbe3ef',backgroundColor:'rgba(255,255,255,0.95)',backdropFilter:'blur(8px)'}}><Toolbar sx={{justifyContent:'space-between',gap:1.5,py:0.75,flexWrap:{xs:'wrap',sm:'nowrap'}}}><Stack direction='row' spacing={1.5} alignItems='center' sx={{minWidth:0}}><Box component='img' src='/logo.png' alt='logo' sx={{width:{xs:34,sm:38},height:{xs:34,sm:38},borderRadius:'50%',flexShrink:0}}/><Typography variant='h6' sx={{fontSize:{xs:'1rem',sm:'1.2rem'},fontWeight:700,lineHeight:1.2}}>FTA VAT & Tax Filing Assistant</Typography></Stack><Stack direction='row' spacing={0.5} sx={{display:{xs:'none',md:'flex'},flexWrap:'wrap',justifyContent:'flex-end'}}>{navLinks.map(l=><Button key={l.label} href={l.href} target='_blank' variant='text' size='small'>{l.label}</Button>)}</Stack><IconButton sx={{display:{md:'none'}}} onClick={e=>setA(e.currentTarget)} aria-label='Open support links'><MenuIcon/></IconButton><Menu anchorEl={a} open={Boolean(a)} onClose={()=>setA(null)}>{navLinks.map(l=><MenuItem key={l.label} component='a' href={l.href} target='_blank'>{l.label}</MenuItem>)}</Menu></Toolbar></AppBar>}
function LiveSummary({mode,vatData,vatCalc,ctCalc}){if(mode==='corporateTax')return <Card><CardContent><Typography variant='h6' sx={{mb:2}}>Corporate Tax Live Summary</Typography><Grid container spacing={2}><Grid size={{xs:12,md:3}}><TaxSummaryCard label='Corporate Tax Estimate' value={money(ctCalc.taxPayable)}/></Grid><Grid size={{xs:12,md:3}}><TaxSummaryCard label='Taxable Income' value={money(ctCalc.taxableIncome)}/></Grid><Grid size={{xs:12,md:3}}><TaxSummaryCard label='Profit Before Tax' value={money(ctCalc.profitBeforeTax)}/></Grid><Grid size={{xs:12,md:3}}><TaxSummaryCard label='Selected Tax Period' value={formatVatPeriodLabel(vatData)}/></Grid></Grid></CardContent></Card>;
const [label,color,amt]=getVatStatus(vatCalc.netVat); return <Card><CardContent><Typography variant='h6' sx={{mb:2}}>VAT Live Summary</Typography><Grid container spacing={2}><Grid size={{xs:12,md:4}}><TaxSummaryCard label={label} value={amt}/><Chip label={label.includes('Refundable')?'REFUNDABLE':label.includes('Payable')?'PAYABLE':'BALANCED'} color={color} sx={{mt:1}}/></Grid><Grid size={{xs:12,md:4}}><TaxSummaryCard label='VAT Taxable Sales' value={money(vatCalc.salesBreakdown.net)}/></Grid><Grid size={{xs:12,md:4}}><TaxSummaryCard label='Selected VAT Period' value={formatVatPeriodLabel(vatData)}/></Grid></Grid></CardContent></Card>}
export function TaxDashboard(){const [m,setM]=React.useState('home'); const [ws]=React.useState(()=>({...workspaceSettingsDefault,...draftStorage.load('workspaceSettings',workspaceSettingsDefault),vatPricingMode:normalizeVatPricingMode(draftStorage.load('workspaceSettings',workspaceSettingsDefault).vatPricingMode)})); const [vat,setVat]=React.useState(()=>normalizeVatDraft(draftStorage.load('vatDraft',vatDefault),ws)); const [ct,setCt]=React.useState(()=>draftStorage.load('ctDraft',ctDefault)); const [vp,setVp]=React.useState(20); const [cp,setCp]=React.useState(17); const v=calculateVat(vat), c=calculateCorporateTax(ct);
return <Box><Header/><Container maxWidth='lg' sx={{py:{xs:2,md:3},px:{xs:1.5,sm:2.5,md:3}}}><Card sx={{mb:2,borderRadius:3,border:'1px solid #dbe3ef',boxShadow:'0 8px 24px rgba(15, 23, 42, .07)'}}><CardContent><Typography component='h1' variant='h4' sx={{fontSize:{xs:'1.35rem',md:'1.7rem'},fontWeight:700,mb:0.8}}>Welcome</Typography><Typography variant='body1' color='text.secondary'>UAE tax workspace for VAT Return and Corporate Tax preparation. Select a module to continue.</Typography></CardContent></Card>
{m==='home'&&<Stack spacing={2.2}><InstallAppPrompt/><Card sx={{borderRadius:3,border:'1px solid #dbe3ef',boxShadow:'0 8px 24px rgba(15, 23, 42, .07)'}}><CardContent><Typography component='h2' variant='h5' sx={{mb:1}}>Choose a tax module</Typography><Typography color='text.secondary' sx={{mb:2}}>Launch a guided workspace with saved drafts, live summaries, and export options.</Typography><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(2, minmax(0,1fr))'},gap:2.2,maxWidth:'100%'}}><TaxModuleCard title='FTA VAT Return' subtitle='Prepare VAT returns with guided period and transaction workflows.' image='/FTA_VAT_RETRUN.png' route='vat' accentColor='border-sky-100 hover:border-sky-300' onSelect={setM}/><TaxModuleCard title='FTA Corporate Tax' subtitle='Estimate corporate tax and organize annual filing data quickly.' image='/FTA_CORPORATE_TAX.png' route='corporateTax' accentColor='border-emerald-100 hover:border-emerald-300' onSelect={setM}/></Box></CardContent></Card><Card sx={{borderRadius:3,border:'1px solid #dbe3ef'}}><CardContent><Typography component='h2' variant='h6' sx={{mb:1}}>Quick Help & Support</Typography><Typography variant='body2' color='text.secondary'>Need filing guidance? Open the official resources below.</Typography><Stack direction='row' useFlexGap flexWrap='wrap' spacing={1} sx={{mt:1.2}}>{navLinks.slice(0,3).map((link)=><Link key={link.label} href={link.href} target='_blank' rel='noreferrer' underline='hover'>{link.label}</Link>)}</Stack></CardContent></Card></Stack>}
{m==='vat'&&<Stack spacing={2}><Button startIcon={<HomeRoundedIcon/>} variant='outlined' sx={{alignSelf:'flex-start'}} onClick={()=>setM('home')}>Back to Home</Button><WorkspaceHeader title='VAT Return Workspace' progress={vp} onBack={()=>setM('home')}/><LiveSummary mode='vat' vatData={vat} vatCalc={v} ctCalc={c}/><VatWizard data={vat} setData={setVat} onProgressChange={setVp} onSave={()=>draftStorage.save('vatDraft',vat)} onReset={()=>{if(confirm('Reset VAT draft?')){const next=normalizeVatDraft(vatDefault,ws);setVat(next);draftStorage.clear('vatDraft');}}}/></Stack>}
{m==='corporateTax'&&<Stack spacing={2}><Button startIcon={<HomeRoundedIcon/>} variant='outlined' sx={{alignSelf:'flex-start'}} onClick={()=>setM('home')}>Back to Home</Button><WorkspaceHeader title='Corporate Tax Workspace' progress={cp} onBack={()=>setM('home')}/><LiveSummary mode='corporateTax' vatData={vat} vatCalc={v} ctCalc={c}/><CorporateTaxWizard data={ct} setData={setCt} onProgressChange={setCp} onSave={()=>draftStorage.save('ctDraft',ct)} onReset={()=>{if(confirm('Reset Corporate Tax draft?')){setCt(ctDefault);draftStorage.clear('ctDraft');}}}/></Stack>}
</Container></Box>}
