import React from 'react';
import { AppBar, Box, Card, CardContent, Chip, Container, Grid, IconButton, LinearProgress, Menu, MenuItem, Stack, Toolbar, Typography, Button } from '@mui/material';
import MenuIcon from '@mui/icons-material/Menu';
import { VatWizard } from './VatWizard';
import { CorporateTaxWizard } from './CorporateTaxWizard';
import { draftStorage } from './lib/localDraftStorage';
import { buildMonthlyEntries, calculateVat } from './lib/vatCalculator';
import { calculateCorporateTax } from './lib/corporateTaxCalculator';
import { money, TaxSummaryCard, WorkspaceHeader } from './components/common.jsx';
import { formatVatPeriodLabel, inferSelectionFromDates, getPeriodFromSelection } from './lib/vatPeriod';
import { VAT_PRICING_MODES, normalizeVatPricingMode } from './lib/vatPricing';
const currentYear=new Date().getFullYear(); const workspaceSettingsDefault={vatPricingMode:VAT_PRICING_MODES.EXCLUSIVE};
const vatDefault={ businessName:'', trn:'', filingFrequency:'Quarterly', filingYear:currentYear, filingMonth:'January', filingQuarter:'Q1', filingStartMonth:'January', taxPeriodStart:'', taxPeriodEnd:'', standardRatedSales:0, zeroRatedSales:0, exemptSales:0, standardRatedPurchases:0, recoverableInputVat:0, nonRecoverableVat:0, previousAdjustment:0, badDebtRelief:0, adjustmentNotes:'', monthlyEntries:[], vatPricingMode:workspaceSettingsDefault.vatPricingMode };
const ctDefault={ companyName:'', taxRegistrationNumber:'', financialYearStart:'', financialYearEnd:'', businessActivity:'', revenue:0, otherIncome:0, exemptIncome:0, directExpenses:0, adminExpenses:0, nonDeductibleExpenses:0, accountingProfit:0, addBackAdjustments:0, deductibleAdjustments:0 };
const navLinks=[{label:'FTA Login',href:'https://eservices.tax.gov.ae/#/Logon'},{label:'VAT Guidelines',href:'https://tax.gov.ae/en/taxes/Vat/vat.topics.aspx'},{label:'Corporate Tax Guidelines',href:'https://tax.gov.ae/en/taxes/corporate.tax/corporate.tax.topics.aspx'},{label:'FTA YouTube',href:'https://www.youtube.com/@uaetax'}];
const getVatStatus=(n)=>n>0?['VAT Payable','error',money(n)]:n<0?['VAT Refundable','success',money(Math.abs(n))]:['VAT Payable / Refundable','primary',money(0)];
const normalizeVatDraft=(input,workspaceSettings)=>{const merged={...vatDefault,...input,vatPricingMode:normalizeVatPricingMode(input?.vatPricingMode||workspaceSettings.vatPricingMode)}; const selection=inferSelectionFromDates(merged); const period=getPeriodFromSelection(selection); const next={...merged,...selection,...period}; next.monthlyEntries=buildMonthlyEntries(next); return next;};
function Header(){const [a,setA]=React.useState(null);return <AppBar position='sticky' color='inherit'><Toolbar sx={{justifyContent:'space-between'}}><Stack direction='row' spacing={1.5} alignItems='center'><Box component='img' src='/logo.png' alt='logo' sx={{width:38,height:38,borderRadius:'50%'}}/><Typography variant='h6'>FTA VAT & Tax Filing Assistant</Typography></Stack><Stack direction='row' spacing={1} sx={{display:{xs:'none',md:'flex'}}}>{navLinks.map(l=><Button key={l.label} href={l.href} target='_blank' variant='text'>{l.label}</Button>)}</Stack><IconButton sx={{display:{md:'none'}}} onClick={e=>setA(e.currentTarget)}><MenuIcon/></IconButton><Menu anchorEl={a} open={Boolean(a)} onClose={()=>setA(null)}>{navLinks.map(l=><MenuItem key={l.label} component='a' href={l.href} target='_blank'>{l.label}</MenuItem>)}</Menu></Toolbar></AppBar>}
function LiveSummary({mode,vatData,vatCalc,ctCalc}){if(mode==='corporateTax')return <Card><CardContent><Typography variant='h6' sx={{mb:2}}>Corporate Tax Live Summary</Typography><Grid container spacing={2}><Grid size={{xs:12,md:3}}><TaxSummaryCard label='Corporate Tax Estimate' value={money(ctCalc.taxPayable)}/></Grid><Grid size={{xs:12,md:3}}><TaxSummaryCard label='Taxable Income' value={money(ctCalc.taxableIncome)}/></Grid><Grid size={{xs:12,md:3}}><TaxSummaryCard label='Profit Before Tax' value={money(ctCalc.profitBeforeTax)}/></Grid><Grid size={{xs:12,md:3}}><TaxSummaryCard label='Selected Tax Period' value={formatVatPeriodLabel(vatData)}/></Grid></Grid></CardContent></Card>;
const [label,color,amt]=getVatStatus(vatCalc.netVat); return <Card><CardContent><Typography variant='h6' sx={{mb:2}}>VAT Live Summary</Typography><Grid container spacing={2}><Grid size={{xs:12,md:4}}><TaxSummaryCard label={label} value={amt}/><Chip label={label.includes('Refundable')?'REFUNDABLE':label.includes('Payable')?'PAYABLE':'BALANCED'} color={color} sx={{mt:1}}/></Grid><Grid size={{xs:12,md:4}}><TaxSummaryCard label='VAT Taxable Sales' value={money(vatCalc.salesBreakdown.net)}/></Grid><Grid size={{xs:12,md:4}}><TaxSummaryCard label='Selected VAT Period' value={formatVatPeriodLabel(vatData)}/></Grid></Grid></CardContent></Card>}
export function TaxDashboard(){const [m,setM]=React.useState('home'); const [ws]=React.useState(()=>({...workspaceSettingsDefault,...draftStorage.load('workspaceSettings',workspaceSettingsDefault),vatPricingMode:normalizeVatPricingMode(draftStorage.load('workspaceSettings',workspaceSettingsDefault).vatPricingMode)})); const [vat,setVat]=React.useState(()=>normalizeVatDraft(draftStorage.load('vatDraft',vatDefault),ws)); const [ct,setCt]=React.useState(()=>draftStorage.load('ctDraft',ctDefault)); const [vp,setVp]=React.useState(20); const [cp,setCp]=React.useState(17); const v=calculateVat(vat), c=calculateCorporateTax(ct);
return <Box><Header/><Container maxWidth='lg' sx={{py:3}}><Card sx={{mb:2}}><CardContent><Typography variant='body2'>UAE Tax Assistant ℹ️ Guided VAT and Corporate Tax filing support.</Typography></CardContent></Card>
{m==='home'&&<Card><CardContent><Typography variant='h5' sx={{mb:1}}>Tax Home</Typography><Typography color='text.secondary' sx={{mb:2}}>Select a module to open a dedicated tax workspace.</Typography><Grid container spacing={2}><Grid size={{xs:12,md:6}}><Box component='img' src='/FTA_VAT_RETRUN.png' sx={{width:'100%',borderRadius:2,cursor:'pointer'}} onClick={()=>setM('vat')}/></Grid><Grid size={{xs:12,md:6}}><Box component='img' src='/FTA_CORPORATE_TAX.png' sx={{width:'100%',borderRadius:2,cursor:'pointer'}} onClick={()=>setM('corporateTax')}/></Grid></Grid></CardContent></Card>}
{m==='vat'&&<Stack spacing={2}><WorkspaceHeader title='VAT Return Workspace' progress={vp} onBack={()=>setM('home')}/><LiveSummary mode='vat' vatData={vat} vatCalc={v} ctCalc={c}/><VatWizard data={vat} setData={setVat} onProgressChange={setVp} onSave={()=>draftStorage.save('vatDraft',vat)} onReset={()=>{if(confirm('Reset VAT draft?')){const next=normalizeVatDraft(vatDefault,ws);setVat(next);draftStorage.clear('vatDraft');}}}/></Stack>}
{m==='corporateTax'&&<Stack spacing={2}><WorkspaceHeader title='Corporate Tax Workspace' progress={cp} onBack={()=>setM('home')}/><LiveSummary mode='corporateTax' vatData={vat} vatCalc={v} ctCalc={c}/><CorporateTaxWizard data={ct} setData={setCt} onProgressChange={setCp} onSave={()=>draftStorage.save('ctDraft',ct)} onReset={()=>{if(confirm('Reset Corporate Tax draft?')){setCt(ctDefault);draftStorage.clear('ctDraft');}}}/></Stack>}
</Container></Box>}
